__title__ = 'django-rest-mock'
__description__ = 'Mock Express server generated based on your views, that can come in handy when developing REST APIs with Django'
__version__ = '0.2.8'
__author__ = 'Thomas Jiang'
__author_email__ = 'thomasjiangcy@gmail.com'
__url__ = 'https://github.com/thomasjiangcy/django-rest-mock-server'
__license__ = 'MIT'
